<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Commandes.Application\Commandes.Application.csproj" />
    <ProjectReference Include="..\Commandes.Contracts\Commandes.Contracts.csproj" />
    <ProjectReference Include="..\Commandes.Domain\Commandes.Domain.csproj" />
  </ItemGroup>

</Project>
