<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Commandes.Application\Commandes.Application.csproj" />
    <ProjectReference Include="..\..\Commandes.Contracts\Commandes.Contracts.csproj" />
    <ProjectReference Include="..\..\Commandes.Domain\Commandes.Domain.csproj" />
    <ProjectReference Include="..\..\..\Drones\Drones.Contracts\Drones.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Catalogue\Catalogue.Contracts\Catalogue.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
